# Generated by Django 5.1.15 on 2026-09-02 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SyncCheckpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=32, unique=True)),
                ('cursor', models.CharField(blank=True, default='', max_length=255)),
                ('last_success_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('idle', 'Idle'), ('running', 'Running'), ('success', 'Success'), ('error', 'Error')], default='idle', max_length=16)),
                ('detail', models.TextField(blank=True, default='')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='LocalIdCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('prefix', models.CharField(max_length=16)),
                ('last_value', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Local ID counter',
                'verbose_name_plural': 'Local ID counters',
                'unique_together': {('year', 'prefix')},
            },
        ),
        migrations.CreateModel(
            name='Vulnerability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vuln_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('title', models.CharField(blank=True, default='', max_length=512)),
                ('description_nvd', models.TextField(blank=True, default='')),
                ('description_bdu', models.TextField(blank=True, default='')),
                ('severity', models.CharField(choices=[('CRITICAL', 'Critical'), ('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low'), ('NONE', 'None'), ('UNKNOWN', 'Unknown')], db_index=True, default='UNKNOWN', max_length=16)),
                ('cvss_v31', models.JSONField(blank=True, null=True)),
                ('cvss_v30', models.JSONField(blank=True, null=True)),
                ('cvss_v2', models.JSONField(blank=True, null=True)),
                ('cvss_v4', models.JSONField(blank=True, null=True)),
                ('cwe', models.JSONField(blank=True, default=list)),
                ('cpe', models.JSONField(blank=True, default=list)),
                ('references', models.JSONField(blank=True, default=list)),
                ('is_kev', models.BooleanField(db_index=True, default=False)),
                ('kev_due_date', models.DateField(blank=True, null=True)),
                ('source', models.CharField(choices=[('NVD', 'NVD'), ('BDU', 'BDU'), ('LOCAL', 'Local'), ('MERGED', 'Merged')], db_index=True, default='NVD', max_length=16)),
                ('published_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('modified_at', models.DateTimeField(blank=True, null=True)),
                ('raw_nvd', models.JSONField(blank=True, null=True)),
                ('raw_bdu', models.JSONField(blank=True, null=True)),
                ('local_seq', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Vulnerability',
                'verbose_name_plural': 'Vulnerabilities',
                'ordering': ['-published_at', '-id'],
                'indexes': [models.Index(fields=['severity', 'is_kev'], name='vulns_vulne_severit_bef713_idx')],
            },
        ),
    ]
