# Generated by Django 5.1.15 on 2026-09-02 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SetupProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_step', models.PositiveSmallIntegerField(default=1)),
                ('completed_steps', models.JSONField(blank=True, default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setup_completed', models.BooleanField(default=False)),
                ('organization_name', models.CharField(blank=True, default='', max_length=255)),
                ('local_id_prefix', models.CharField(blank=True, default='', max_length=16)),
                ('login_title', models.CharField(blank=True, default='NovaTIP', max_length=255)),
                ('login_subtitle', models.TextField(blank=True, default='Threat Intelligence Platform')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='branding/')),
                ('nvd_api_key', models.CharField(blank=True, default='', max_length=255)),
                ('kev_enabled', models.BooleanField(default=True)),
                ('bdu_enabled', models.BooleanField(default=True)),
                ('sync_cron', models.CharField(blank=True, default='0 * * * *', max_length=64)),
                ('email_host', models.CharField(blank=True, default='', max_length=255)),
                ('email_port', models.PositiveIntegerField(default=587)),
                ('email_user', models.CharField(blank=True, default='', max_length=255)),
                ('email_password', models.CharField(blank=True, default='', max_length=255)),
                ('email_use_tls', models.BooleanField(default=True)),
                ('telegram_bot_token', models.CharField(blank=True, default='', max_length=255)),
                ('telegram_chat_id', models.CharField(blank=True, default='', max_length=64)),
                ('db_host', models.CharField(blank=True, default='127.0.0.1', max_length=255)),
                ('db_port', models.PositiveIntegerField(default=5432)),
                ('db_name', models.CharField(blank=True, default='novatip', max_length=128)),
                ('db_user', models.CharField(blank=True, default='novatip', max_length=128)),
                ('db_sslmode', models.CharField(blank=True, default='prefer', max_length=32)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'System settings',
                'verbose_name_plural': 'System settings',
            },
        ),
    ]
