# Generated by Django 5.1.15 on 2026-09-02 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LicenseState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('valid', 'Valid'), ('grace', 'Grace'), ('invalid', 'Invalid'), ('missing', 'Missing')], default='missing', max_length=16)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('grace_until', models.DateTimeField(blank=True, null=True)),
                ('fingerprint', models.CharField(blank=True, default='', max_length=128)),
                ('server_url', models.URLField(blank=True, default='')),
                ('last_check_at', models.DateTimeField(blank=True, null=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('public_notes', models.TextField(blank=True, default='')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'License state',
                'verbose_name_plural': 'License state',
            },
        ),
    ]
